apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-client
  template:
    metadata:
      labels:
        app: mcp-client
    spec:
      containers:
      - name: mcp-client
        image: mcp-amqp:latest
        imagePullPolicy: Never
        command: ["uvx", "amq-mcp-server-rabbitmq@latest", "--allow-mutative-tool"]
