apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-interceptor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor-interceptor
  template:
    metadata:
      labels:
        app: monitor-interceptor
    spec:
      containers:
      - name: monitor-interceptor
        image: monitor-interceptor:latest
        imagePullPolicy: Never
        command:
        - node
        - dist/src/monitor_cli.js
        - $(IN_EXCHANGE)
        - $(OUT_EXCHANGE)
        env:
        - name: AMQP_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: monitor-interceptor-config
              key: AMQP_HOSTNAME
        - name: AMQP_PORT
          valueFrom:
            configMapKeyRef:
              name: monitor-interceptor-config
              key: AMQP_PORT
        - name: AMQP_USERNAME
          valueFrom:
            configMapKeyRef:
              name: monitor-interceptor-config
              key: AMQP_USERNAME
        - name: AMQP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: amqp-secret
              key: AMQP_PASSWORD
        - name: AMQP_USE_TLS
          value: "true"
        - name: IN_EXCHANGE
          valueFrom:
            configMapKeyRef:
              name: monitor-interceptor-config
              key: IN_EXCHANGE
        - name: OUT_EXCHANGE
          valueFrom:
            configMapKeyRef:
              name: monitor-interceptor-config
              key: OUT_EXCHANGE
        - name: LOG_GROUP_NAME
          value: "/mcp/monitor"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_REGION
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: AWS_REGION
