FROM node:20-slim

WORKDIR /app

COPY amazon_mq_github/mcp-amqp-transport/package*.json ./
RUN npm install

COPY amazon_mq_github/mcp-amqp-transport/ ./
RUN npm run build && npm link

ENV PATH="/root/.local/bin:${PATH}"


WORKDIR /interceptor

COPY mcp_cluster_demo/interceptors_cluster/opensearch-logger/package*.json ./
RUN npm install

COPY mcp_cluster_demo/interceptors_cluster/opensearch-logger/ ./
RUN npm run build