[project]
name = "rabbitmq-strands-agent"
version = "0.1.0"
description = "Strands agent for RabbitMQ MCP server"
requires-python = ">=3.10"
dependencies = [
    "strands-agents>=1.12.0",
    "mcp>=1.0.0",
]